name: Auto Fix Style

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: autofix-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  detect-changes:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    outputs:
      cs: ${{ steps.filter.outputs.cs }}
      bicep: ${{ steps.filter.outputs.bicep }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event.pull_request.base.sha }}
          ref: ${{ github.event.pull_request.head.sha }}
          filters: |
            cs:
              - '**/*.cs'
            bicep:
              - '**/*.bicep'
            frontend:
              - '**/*.js'
              - '**/*.ts'
              - '**/*.tsx'

  autofix:
    needs: detect-changes
    if: ${{ github.actor != 'github-actions[bot]' && (
      needs.detect-changes.outputs.cs == 'true' ||
      needs.detect-changes.outputs.bicep == 'true' ||
      needs.detect-changes.outputs.frontend == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - if: needs.detect-changes.outputs.cs == 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - if: needs.detect-changes.outputs.cs == 'true'
        run: |
          cd src/OTP
          dotnet format OTP.sln --severity info
          dotnet format analyzers --severity info

      - if: needs.detect-changes.outputs.bicep == 'true'
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install
      - if: needs.detect-changes.outputs.bicep == 'true'
        run: |
          shopt -s nullglob
          for f in infrastructure/bicep/**/*.bicep infrastructure/bicep/*.bicep; do
            bicep format "$f"
          done
          shopt -u nullglob

      - if: needs.detect-changes.outputs.frontend == 'true'
        run: |
          npm ci || true
          npx eslint . --ext .js,.ts,.tsx --fix || true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply auto-format [autofix] [skip ci]"
          branch: ${{ github.head_ref }}
