name: Deploy OTP Infra

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment
        run: |
          az deployment sub validate --template-file infrastructure/bicep/main.bicep --location=westeurope

      - name: Validate resource group deployment
        run: |
          az deployment group validate --resource-group rg-environment-dev --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/dev/main.otp.dev.parameters.json)"

      - name: Create Resource Groups (subscription level)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-dev

      - name: Deploy OTP resources (resource group level)
        run: |
          az deployment group create --name deploy-otp-dev --resource-group rg-environment-dev --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/dev/main.otp.dev.parameters.json)"
          
      - name: Set secrets in Key Vault
        if: success()
        run: |
          kvName=$(az deployment group show \
            --resource-group rg-environment-dev \
            --name deploy-otp-dev \
            --query "properties.outputs.keyVaultName.value" \
            --output tsv)

          az keyvault secret set --vault-name $kvName --name OtpSecretKey --value "${{ secrets.OTP_SECRET }}"
          az keyvault secret set --vault-name $kvName --name SqlAdminPassword --value "${{ secrets.SQL_ADMIN_PASSWORD }}"

      - name: Show deployment logs on failure
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-dev --name deploy-otp-dev || echo "No deployment found (likely validation failure)"
          

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment
        run: |
          az deployment sub validate --template-file infrastructure/bicep/main.bicep --location=westeurope

      - name: Validate resource group deployment
        run: |
          az deployment group validate --resource-group rg-environment-test --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/test/main.otp.test.parameters.json)"

      - name: Create Resource Groups (subscription level)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-test

      - name: Deploy OTP resources (resource group level)
        run: |
          az deployment group create --name deploy-otp-test --resource-group rg-environment-test --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/test/main.otp.test.parameters.json)"
          
      - name: Set secrets in Key Vault
        if: success()
        run: |
          kvName=$(az deployment group show \
            --resource-group rg-environment-test \
            --name deploy-otp-test \
            --query "properties.outputs.keyVaultName.value" \
            --output tsv)

          az keyvault secret set --vault-name $kvName --name OtpSecretKey --value "${{ secrets.OTP_SECRET }}"
          az keyvault secret set --vault-name $kvName --name SqlAdminPassword --value "${{ secrets.SQL_ADMIN_PASSWORD }}"

      - name: Show deployment logs on failure
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-test --name deploy-otp-test || echo "No deployment found (likely validation failure)"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment
        run: |
          az deployment sub validate --template-file infrastructure/bicep/main.bicep --location=westeurope

      - name: Validate resource group deployment
        run: |
          az deployment group validate --resource-group rg-environment-prod --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/prod/main.otp.prod.parameters.json)"

      - name: Create Resource Groups (subscription level)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-prod

      - name: Deploy OTP resources (resource group level)
        run: |
          az deployment group create --name deploy-otp-prod --resource-group rg-environment-prod --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/prod/main.otp.prod.parameters.json)"
          
      - name: Set secrets in Key Vault
        if: success()
        run: |
          kvName=$(az deployment group show \
            --resource-group rg-environment-prod \
            --name deploy-otp-prod \
            --query "properties.outputs.keyVaultName.value" \
            --output tsv)

          az keyvault secret set --vault-name $kvName --name OtpSecretKey --value "${{ secrets.OTP_SECRET }}"
          az keyvault secret set --vault-name $kvName --name SqlAdminPassword --value "${{ secrets.SQL_ADMIN_PASSWORD }}"


      - name: Show deployment logs on failure
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-prod --name deploy-otp-prod || echo "No deployment found (likely validation failure)"