name: Deploy OTP Infra

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:  
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}     

      - name: Create Resource Groups (subscription level)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-dev --parameters environment=dev

      - name: Deploy OTP resources (resource group level)
        run: |
          az deployment group create --name deploy-otp-dev --resource-group rg-otp-dev --template-file infrastructure/bicep/main.otp.bicep --parameters @infrastructure/bicep/env/dev/main.otp.dev.parameters.json --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD }}" --parameters githubSpObjectId="${{ secrets.SP_OBJECT_ID_GITHUB }}"         
                
      - name: Set secrets in Key Vault
        if: success()
        run: |
          kvName=$(az deployment group show \
            --resource-group rg-otp-dev \
            --name deploy-otp-dev \
            --query "properties.outputs.keyVaultName.value" \
            --output tsv)

          if [ -z "$kvName" ]; then
            echo "Key Vault name was not returned by deployment. Exiting."
            exit 1
          fi

          az keyvault secret set --vault-name "$kvName" --name OtpSecretKey --value "${{ secrets.OTP_SECRET }}"
          az keyvault secret set --vault-name "$kvName" --name SqlAdminPassword --value "${{ secrets.SQL_ADMIN_PASSWORD }}"
          
      - name: Set OtpDatabaseConnection in Azure App Settings
        if: success()
        run: |
          funcAppName=$(az deployment group show \
            --resource-group rg-otp-dev \
            --name deploy-otp-dev \
            --query "properties.outputs.functionAppName.value" \
            --output tsv)

          az functionapp config appsettings set \
            --name $funcAppName \
            --resource-group rg-otp-dev \
            --settings OtpDatabaseConnection="${{ secrets.SQL_CONNECTION_STRING_DEV }}"
          
      - name: Show deployment logs on failure
        if: failure()
        run: |
          az deployment group show --resource-group rg-otp-dev --name deploy-otp-dev || echo "No deployment found (likely validation failure)"
          

  deploy-test:
    runs-on: ubuntu-latest
    environment: test    
    needs: deploy-dev
    
    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      
      
      - name: Create Resource Groups (subscription level)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-test --parameters environment=test

      - name: Deploy OTP resources (resource group level)
        run: |
          az deployment group create --name deploy-otp-test --resource-group rg-otp-test --template-file infrastructure/bicep/main.otp.bicep --parameters @infrastructure/bicep/env/test/main.otp.test.parameters.json --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD }}" --parameters githubSpObjectId="${{ secrets.SP_OBJECT_ID_GITHUB }}"
          
      - name: Set secrets in Key Vault
        if: success()
        run: |
          kvName=$(az deployment group show \
            --resource-group rg-otp-test \
            --name deploy-otp-test \
            --query "properties.outputs.keyVaultName.value" \
            --output tsv)

          az keyvault secret set --vault-name $kvName --name OtpSecretKey --value "${{ secrets.OTP_SECRET }}"
          az keyvault secret set --vault-name $kvName --name SqlAdminPassword --value "${{ secrets.SQL_ADMIN_PASSWORD }}"
          
      - name: Set OtpDatabaseConnection in Azure App Settings
        if: success()
        run: |
         funcAppName=$(az deployment group show \
            --resource-group rg-otp-test \
            --name deploy-otp-test \
            --query "properties.outputs.functionAppName.value" \
            --output tsv)

          az functionapp config appsettings set \
            --name $funcAppName \
            --resource-group rg-otp-test \
            --settings OtpDatabaseConnection="${{ secrets.SQL_CONNECTION_STRING_TEST }}"
          
      - name: Show deployment logs on failure
        if: failure()
        run: |
          az deployment group show --resource-group rg-otp-test --name deploy-otp-test || echo "No deployment found (likely validation failure)"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod    
    needs: deploy-test

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Create Resource Groups (subscription level)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-prod --parameters environment=prod

      - name: Deploy OTP resources (resource group level)
        run: |
          az deployment group create --name deploy-otp-prod --resource-group rg-otp-prod --template-file infrastructure/bicep/main.otp.bicep --parameters @infrastructure/bicep/env/prod/main.otp.prod.parameters.json --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD }}" --parameters githubSpObjectId="${{ secrets.SP_OBJECT_ID_GITHUB }}"
          
      - name: Set secrets in Key Vault
        if: success()
        run: |
          kvName=$(az deployment group show \
            --resource-group rg-otp-prod \
            --name deploy-otp-prod \
            --query "properties.outputs.keyVaultName.value" \
            --output tsv)

          az keyvault secret set --vault-name $kvName --name OtpSecretKey --value "${{ secrets.OTP_SECRET }}"
          az keyvault secret set --vault-name $kvName --name SqlAdminPassword --value "${{ secrets.SQL_ADMIN_PASSWORD }}"
          
      - name: Set OtpDatabaseConnection in Azure App Settings
        if: success()
        run: |
          funcAppName=$(az deployment group show \
            --resource-group rg-otp-prod \
            --name deploy-otp-prod \
            --query "properties.outputs.functionAppName.value" \
            --output tsv)

          az functionapp config appsettings set \
            --name $funcAppName \
            --resource-group rg-otp-prod \
            --settings OtpDatabaseConnection="${{ secrets.SQL_CONNECTION_STRING_PROD }}"          

      - name: Show deployment logs on failure
        if: failure()
        run: |
          az deployment group show --resource-group rg-otp-prod --name deploy-otp-prod || echo "No deployment found (likely validation failure)"