name: Deploy OTP Infra

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment (dev)
        run: |
          az deployment sub validate --template-file infrastructure/bicep/main.bicep --location=westeurope

      - name: Validate resource group deployment (dev)
        run: |
          az deployment group validate --resource-group rg-environment-dev --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/dev/main.otp.dev.parameters.json)"

      - name: Create Resource Groups (subscription level) (dev)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-dev

      - name: Deploy OTP resources (resource group level) (dev)
        run: |
          az deployment group create --name deploy-otp-dev --resource-group rg-environment-dev --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/dev/main.otp.dev.parameters.json)"

      - name: Show deployment logs on failure (dev)
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-dev --name deploy-otp-dev || echo "No deployment found (likely validation failure)"
          

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment (test)
        run: |
          az deployment sub validate --template-file infrastructure/bicep/main.bicep --location=westeurope

      - name: Validate resource group deployment (test)
        run: |
          az deployment group validate --resource-group rg-environment-test --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/test/main.otp.test.parameters.json)"

      - name: Create Resource Groups (subscription level) (test)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-test

      - name: Deploy OTP resources (resource group level) (test)
        run: |
          az deployment group create --name deploy-otp-test --resource-group rg-environment-test --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/test/main.otp.test.parameters.json)"

      - name: Show deployment logs on failure (test)
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-test --name deploy-otp-test || echo "No deployment found (likely validation failure)"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment (prod)
        run: |
          az deployment sub validate --template-file infrastructure/bicep/main.bicep --location=westeurope

      - name: Validate resource group deployment (prod)
        run: |
          az deployment group validate --resource-group rg-environment-prod --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/prod/main.otp.prod.parameters.json)"

      - name: Create Resource Groups (subscription level) (prod)
        run: |
          az deployment sub create --template-file infrastructure/bicep/main.bicep --location=westeurope --name deploy-rg-prod

      - name: Deploy OTP resources (resource group level) (prod)
        run: |
          az deployment group create --name deploy-otp-prod --resource-group rg-environment-prod --template-file infrastructure/bicep/main.otp.bicep --parameters "$(cat infrastructure/bicep/env/prod/main.otp.prod.parameters.json)"

      - name: Show deployment logs on failure (prod)
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-prod --name deploy-otp-prod || echo "No deployment found (likely validation failure)"