name: Deploy OTP Infra

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment (dev)
        run: |
          az deployment sub validate --template-file bicep/main.bicep --location=westeurope --parameters environment=dev

      - name: Validate resource group deployment (dev)
        run: |
          az deployment group validate --resource-group rg-environment-dev --template-file bicep/main.otp.bicep --parameters @bicep/env/dev/main.otp.dev.parameters.json

      - name: Deploy Resource Groups (subscription level) (dev)
        run: |
          az deployment sub create --template-file bicep/main.bicep --location=westeurope --parameters environment=dev

      - name: Deploy OTP resources (resource group level) (dev)
        run: |
          az deployment group create --resource-group rg-environment-dev --template-file bicep/main.otp.bicep --parameters @bicep/env/dev/main.otp.dev.parameters.json

      - name: Show deployment logs on failure (dev)
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-dev --name deploy-otp

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment (test)
        run: |
          az deployment sub validate --template-file bicep/main.bicep --location=westeurope --parameters environment=test

      - name: Validate resource group deployment (test)
        run: |
          az deployment group validate --resource-group rg-environment-test --template-file bicep/main.otp.bicep --parameters @bicep/env/test/main.otp.test.parameters.json

      - name: Deploy Resource Groups (subscription level) (test)
        run: |
          az deployment sub create --template-file bicep/main.bicep --location=westeurope --parameters environment=test

      - name: Deploy OTP resources (resource group level) (test)
        run: |
          az deployment group create --resource-group rg-environment-test --template-file bicep/main.otp.bicep --parameters @bicep/env/test/main.otp.test.parameters.json

      - name: Show deployment logs on failure (test)
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-test --name deploy-otp

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade Azure CLI
        run: az upgrade --yes

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate subscription deployment (prod)
        run: |
          az deployment sub validate --template-file bicep/main.bicep --location=westeurope --parameters environment=prod

      - name: Validate resource group deployment (prod)
        run: |
          az deployment group validate --resource-group rg-environment-prod --template-file bicep/main.otp.bicep --parameters @bicep/env/prod/main.otp.prod.parameters.json

      - name: Deploy Resource Groups (subscription level) (prod)
        run: |
          az deployment sub create --template-file bicep/main.bicep --location=westeurope --parameters environment=prod

      - name: Deploy OTP resources (resource group level) (prod)
        run: |
          az deployment group create --resource-group rg-environment-prod --template-file bicep/main.otp.bicep --parameters @bicep/env/prod/main.otp.prod.parameters.json

      - name: Show deployment logs on failure (prod)
        if: failure()
        run: |
          az deployment group show --resource-group rg-environment-prod --name deploy-otp